FROM nginx:1.29-alpine
RUN apk add --no-cache curl
RUN rm -f /etc/nginx/conf.d/default.conf
COPY tests/docker/stress/nginx.conf /etc/nginx/nginx.conf
COPY tests/docker/stress/uwsgi_params /etc/nginx/uwsgi_params
EXPOSE 8461 8463 8464 8466
