from signal import Signals
from types import FrameType

from _typeshed import Incomplete

from gunicorn.workers.base import Worker

class TornadoWorker(Worker):
    @classmethod
    def setup(cls) -> None: ...
    def handle_exit(self, sig: Signals, frame: FrameType | None) -> None: ...
    alive: bool
    def handle_request(self) -> None: ...
    def watchdog(self) -> None: ...
    server_alive: bool
    def heartbeat(self) -> None: ...
    def init_process(self) -> None: ...
    ioloop: Incomplete
    callbacks: Incomplete
    server: Incomplete
    def run(self) -> None: ...
