from _typeshed import Incomplete

from gunicorn import util as util
from gunicorn.config import Config as Config

PLATFORM: Incomplete
IS_CYGWIN: Incomplete

class WorkerTmp:
    def __init__(self, cfg: Config) -> None: ...
    def notify(self) -> None: ...
    def last_update(self) -> float: ...
    def fileno(self) -> int: ...
    def close(self) -> None: ...
