test-warnings: true

ignore-paths:
  - gunicorn/_compat.py
  - gunicorn/argparse_compat.py
  - gunicorn/selectors.py
  - gunicorn/six.py
  - build
  - docs
  - examples
  - scripts
  - tests/requests/valid
  - tests/requests/invalid

pep8:
  disable:
    - E126
    - E128
    - E129
    - E302
    - E501

pyflakes:
  disable:
    # Redefinition of unused $X from line $LINE
    - F811
    # Access to a protected member $X of a client class
    - W0212

pylint:
  disable:
    - bare-except
    - duplicate-bases
    - duplicate-except
    - eval-used
    - import-error
    - import-self
    - logging-not-lazy
    - no-staticmethod-decorator
    - not-callable
    - not-context-manager
    - pointless-statement
    - protected-access
    - redefined-builtin
    - too-many-arguments
    - too-many-branches
    - too-many-function-args
    - too-many-locals
    - too-many-nested-blocks
    - unused-argument
    - unused-import
    - unused-variable
    - wrong-import-position

mccabe:
  run: false
