test-warnings: true

ignore-paths:
  - gunicorn/_compat.py
  - gunicorn/argparse_compat.py
  - gunicorn/selectors.py
  - gunicorn/six.py
  - build
  - docs
  - examples
  - scripts
  - tests/requests/valid
  - tests/requests/invalid
  - tests/treq.py  # We are going to replace this with pytest.
  - tests/t.py  # Same as above.
  - tests/test_selectors.py  # This basically port of upstream selectors tests.
  - tests/test_gaiohttp.py  # TODO: We are going to remove this worker.

pep8:
  enable:
    - E127
    - E128
    - E262
    - E265
    - E266
    - E301
    - E302
    - E303
    - W291
    - W293
  disable:
    - E129

pyflakes:
  run: false

pylint:
  disable:
    - bare-except
    - misplaced-comparison-constant
    - protected-access
    - import-error
    - too-many-branches
    - too-many-arguments
    - too-many-nested-blocks
    - eval-used
    - no-else-return
    - wrong-import-position
    - unused-argument
    - import-self
    - duplicate-bases
    - no-staticmethod-decorator
    - not-callable

mccabe:
  run: false
