image: Ubuntu
version: '{branch}.{build}'
environment:
  matrix:
    - TOXENV: lint
    - TOXENV: docs-lint
    - TOXENV: pycodestyle
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310  # Not yet present on Appveyor Ubuntu image
install:
  - pip install --upgrade pip
  - pip install tox
build: false
test_script:
  - tox
notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
