# appveyor.yml
---
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux
# https://www.appveyor.com/docs/lang/python

image: Ubuntu
version: '{branch}.{build}'
environment:
  matrix:
    - TOXENV: lint
    - TOXENV: docs-lint
    - TOXENV: pycodestyle
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    # - TOXENV: py310  # Not yet present on Appveyor Ubuntu image
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install tox
build: false
test_script:
  - python3 -m tox
notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
