# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
environment:
  matrix:
  - TOXENV: lint
    PYTHON: C:\\Python38-x64
  - TOXENV: docs-lint
    PYTHON: C:\\Python38-x64
  - TOXENV: pycodestyle
    PYTHON: C:\\Python38-x64
  - TOXENV: py36
    PYTHON: C:\\Python36-x64
  - TOXENV: py37
    PYTHON: C:\\Python37-x64
  - TOXENV: py38
    PYTHON: C:\\Python38-x64
  #- TOXENV: py39
  #  PYTHON: "C:\\Python39-x64"
  #- TOXENV: py310
  #  PYTHON: "C:\\Python310-x64"

build: off

install:
# - dir C:\Py*  # Python 2.{6,7}, 3{3,4,5,6,7,8} but NOT 3.9 and 3.10
- py -0  # See all installed Pythons
- py -VV  # Python 3.8.0 -- py -3.8-64 or -3.8-32
- py -3.6 --version || true
- py -3.7 --version || true
- py -3.8 --version || true
#- py -3.9 --version || true
#- py -3-10 --version || true
- py -3.8-64 -m pip install --upgrade pip
- py -3.8-64 -m pip install tox

test_script:
- py -3.8-64 -m tox
