# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
environment:
  matrix:
  - TOXENV: lint
  - TOXENV: docs-lint
  - TOXENV: pycodestyle
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310

build: off

install:
- pip install tox

test_script:
- tox
