# appveyor.yml
---
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux
# https://www.appveyor.com/docs/lang/python

image: Ubuntu
version: '{branch}.{build}'
environment:
  matrix:
    - TOXENV: lint
      stack: python 3.9
    - TOXENV: docs-lint
      stack: python 3.9
    - TOXENV: pycodestyle
      stack: python 3.9
    - TOXENV: py36
      stack: python 3.6
    - TOXENV: py37
      stack: python 3.7
    - TOXENV: py38
      stack: python 3.8
    - TOXENV: py39
      stack: python 3.9
    # - TOXENV: py310  # Not yet present on Appveyor Ubuntu image
install:
  - pip install --upgrade pip
  - pip install tox
build: false
test_script:
  - tox
notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
