# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019
version: '{branch}.{build}'
environment:
  matrix:
    - PY_VER: "3.5"
      TOXENV: py35
    - PY_VER: "3.6"
      TOXENV: py36
    - PY_VER: "3.7"
      TOXENV: py37
    - PY_VER: "3.8"
      TOXENV: py38
    - PY_VER: "3.9"
      TOXENV: py39
    - PY_VER: "3.10"
      TOXENV: py310
build: false
install:     py -$PY_VER -m pip install tox
test_script: py -$PY_VER -m tox
cache:
  # Not including the .tox directory since it takes longer to download/extract
  # the cache archive than for tox to clean install from the pip cache.
  - '%LOCALAPPDATA%\pip\Cache -> tox.ini'
notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
