from _typeshed import Incomplete

class Pidfile:
    fname: str
    pid: int | None

    def __init__(self, fname: str) -> None: ...
    def create(self, pid: int) -> None: ...
    def rename(self, path: str) -> None: ...
    def unlink(self) -> None: ...
    def validate(self) -> None: ...
