from gunicorn.sock import TCPSocket as TCPSocket

def set_owner_process(
    uid: int | None, gid: int | None, initgroups: bool = ...
) -> None: ...
def close_on_exec(fd: int | TCPSocket) -> None: ...
def resolve_uid(val: str) -> int: ...
def resolve_gid(val: str) -> int: ...
def pipe2() -> tuple[int, int]: ...
def _get_username(uid: int) -> str: ...
def matching_effective_uid_gid(uid: int | None, gid: int | None) -> bool: ...

ALL = [
    "close_on_exec",
    "matching_effective_uid_gid",
    "pipe2",
    "resolve_gid",
    "resolve_uid",
    "set_owner_process",
]
