# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
name: Feature Request
description: Request a new feature or modified default behaviour
# could always prepend title, but that leads to odd titles when reporter is unaware
# title: "[FR]: "
# title: "[RFF]: "
# need to cleanup existing labels before adding this
# labels: ["- Features -"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements for Gunicorn.
        As limited time can be spent on triaging, we would appreciate if you
          * look for existing requests that may match yours
          * link references, if you are asking about internet standards
          * include in your considerations about future maintenance
  - type: textarea
    id: what-problem
    attributes:
      label: What problem would like like to see solved
      description: How is what you want to do not currently easily achieved with gunicorn?
      placeholder: Currently returning baz is limited to one foo.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: How would you like to see the problem solved
      description: Please be specific. Explicitly mention what existing functionality that might be impacted.
      placeholder: I would modify the X component to accept Y also for in the Z case. The B case for Y will remain untouched. The A case will stop working, but that could have never worked due to C anyway.
