#!/bin sh

if [ -f /var/run/gunicorn.pid ]; then
  rm /var/run/gunicorn.pid
fi

cd /path/to/project
exec /usr/local/bin/gunicorn -C /path/to/project/gunicorn.conf.py \
  --pidfile=/var/run/gunicorn.pid main:application