name: release

on:
  push:
    tags:
     - '*'
  # FIXME: enable for for CI-triggered pypi uploads:
  # release:
  #   types:
  #     - published
  workflow_dispatch:
  # https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow

permissions:
  contents: read
  # FIXME: enable for "trusted" publishing:
  # id-token: write

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: gunicorn
      # FIXME: this is just the TEST pypi url!
      url: https://test.pypi.org/p/gunicorn
    steps:
     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
     - name: Install dist Dependencies
       run: |
         python -m pip install build
     - run: python -m build
     - name: do release
       if: ${{ github.event_name == 'release' }}
       uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
       with:
         # FIXME: this is just the TEST pypi url!
         repository-url: https://test.pypi.org/legacy/
         verbose: true
